### ISSUE TITLE
请问如何获得locust的http_client_session实例？

### ISSUE THREAD

**Issue by WilliamSkyWalker** [debugtalk/ApiTestEngine#1]
是HttpLocust.http_client_session吗？

**Comment by debugtalk** [comment]
不应该是在单元测试里面去调用Locust，而应该是在通过Locust进行性能测试时，将HttpLocust的实例传给测试代码。针对这一块儿，我右面会有详细讲解的。

**Comment by YanQinYuan** [comment]
请问要如何启用该程序

**Comment by debugtalk** [comment]
@YanQinYuan 

```bash
$ python main.py --testcase-path TESTCASE_PATH
```

TESTCASE_PATH 是用例的路径。

后面我会添加详细示例进行说明的。

**Comment by YanQinYuan** [comment]
谢谢解答。
