### ISSUE TITLE
不支持https 吗 

### ISSUE THREAD

**Issue by muxiaFrank** [debugtalk/ApiTestEngine#15]
跑https  提示exception msg: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')

**Comment by debugtalk** [comment]
@muxiaFrank 底层是完全复用的requests，所以只要requests支持的功能，这款框架都支持。另外，如果你测试的https网站没有证书，你可以采用 verify=False 来关闭校验。

参考链接：http://docs.python-requests.org/en/master/api/#requests.request

**Comment by diaojunxian** [comment]
请教一下，我最近遇到一个新需求，需要持久化存储每次执行完的某个接口的返回值。这个如何能在框架内实现呢？

--------------------------------------------------------------------------------------------------------------------

在 2017年8月9日，上午10:38，Leo Lee (九毫) <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #15<https://github.com/debugtalk/ApiTestEngine/issues/15>.

**Comment by debugtalk** [comment]
@diaojunxian 运行测试时，增加`--log-level debug`是可以将详细的请求和响应打印出来；但要做持久化存储，那就需要再引入数据库或者文件存储了。

**Comment by chenwenbin69** [comment]
> @muxiaFrank 底层是完全复用的requests，所以只要requests支持的功能，这款框架都支持。另外，如果你测试的https网站没有证书，你可以采用 verify=False 来关闭校验。
> 
> 参考链接：http://docs.python-requests.org/en/master/api/#requests.request

![image](https://user-images.githubusercontent.com/39043837/58469114-72dec380-8171-11e9-9115-aa5fdd31b5a9.png)
请问我在json中把verify的值设为False为啥报错呢？报错信息如下
![image](https://user-images.githubusercontent.com/39043837/58469234-af122400-8171-11e9-9b72-6ff70a183515.png)
