### ISSUE TITLE
感谢分享！同时想请教下楼主几个问题

### ISSUE THREAD

**Issue by YanQinYuan** [debugtalk/ApiTestEngine#21]
1，如果要做一些复杂的断言，如：提取返回的html里的某一个值和预期作断言，应该如何做？
2，如果接口返回的数据是用des+base64加密，要怎么做断言？
3，能否用数据驱动的方式编写用例

**Comment by debugtalk** [comment]
@YanQinYuan 

1，当前的框架还只支持请求响应都是JSON数据结构的接口，对于响应结果为`html`的情况，这一块儿需求还未实现，但已提上日程；
2，接口返回数据采用`des+base64`加密后，不知道你需要判断什么，简单地，你可以通过对加密后的字符串进行正则匹配；如果你需要判断是否加密正确，那么就需要在Python模块中也实现一套同样的加密算法函数，然后传参调用计算得到一个结果，最后再在校验结果里进行比对。

**Comment by debugtalk** [comment]
@YanQinYuan 另外，麻烦后续提问的时候对不同类型的问题分开issue进行提问，这样方便进行标记，谢谢啦！

**Comment by debugtalk** [comment]
1、已经支持对返回结果为html的情况进行解析和断言：http://debugtalk.com/post/apitestengine-not-only-about-json-api/
3、已经支持数据驱动：http://cn.httprunner.org/data-driven/
