### ISSUE TITLE
如何采用ApiTestEngine实现性能测试？

### ISSUE THREAD

**Issue by Xhao123456** [debugtalk/ApiTestEngine#24]
对写好的测试用例使用locust做压测该怎么做啊？是需要重新早用python写一遍再压测吗？

**Comment by debugtalk** [comment]
@Xhao123456 当然不用。运行`ate-locust -h`试试。

https://github.com/debugtalk/ApiTestEngine/tree/locust

**Comment by Xhao123456** [comment]
找不到命令。。。是要将ate和locust都更新为最新版本吗？我的locust还是0.7.5，ate是2周以前的

**Comment by debugtalk** [comment]
@Xhao123456 是我之前没有将master分支与locust分支合并。现在已经合并了，你重新安装就有了。

**Comment by Junho2010** [comment]
C:\Users\hexia>python3 -m pip install -U locust
Collecting locust
  Could not find a version that satisfies the requirement locust (from versions: )
No matching distribution found for locust

C:\Users\hexia>python3 -m pip install -U locustio
Requirement already up-to-date: locustio in c:\python36\lib\site-packages
Requirement already up-to-date: requests>=2.9.1 in c:\python36\lib\site-packages (from locustio)
Requirement already up-to-date: gevent==1.1.1 in c:\python36\lib\site-packages (from locustio)
Requirement already up-to-date: flask>=0.10.1 in c:\python36\lib\site-packages (from locustio)
Requirement already up-to-date: msgpack-python>=0.4.2 in c:\python36\lib\site-packages (from locustio)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in c:\python36\lib\site-packages (from requests>=2.9.1->locustio)
Requirement already up-to-date: idna<2.7,>=2.5 in c:\python36\lib\site-packages (from requests>=2.9.1->locustio)
Requirement already up-to-date: certifi>=2017.4.17 in c:\python36\lib\site-packages (from requests>=2.9.1->locustio)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in c:\python36\lib\site-packages (from requests>=2.9.1->locustio)
Requirement already up-to-date: greenlet>=0.4.9 in c:\python36\lib\site-packages (from gevent==1.1.1->locustio)
Requirement already up-to-date: click>=2.0 in c:\python36\lib\site-packages (from flask>=0.10.1->locustio)
Requirement already up-to-date: itsdangerous>=0.21 in c:\python36\lib\site-packages (from flask>=0.10.1->locustio)
Requirement already up-to-date: Werkzeug>=0.7 in c:\python36\lib\site-packages (from flask>=0.10.1->locustio)
Requirement already up-to-date: Jinja2>=2.4 in c:\python36\lib\site-packages (from flask>=0.10.1->locustio)
Requirement already up-to-date: MarkupSafe>=0.23 in c:\python36\lib\site-packages (from Jinja2>=2.4->flask>=0.10.1->locustio)

C:\Users\hexia>ate-locust -h
Locust is not installed, exit.

一直提示没有安装Locust，自己测试是安装了的

**Comment by debugtalk** [comment]
@Junho2010 你直接执行 `locust -h` 是正常的么？

你要是看了源码就会发现，其实在调用的时候，就是调用的`locust -h`。

```python
def main_locust():
    """ Performance test with locust: parse command line options and run commands.
    """
    try:
        from locust.main import main
    except ImportError:
        print("Locust is not installed, exit.")
        exit(1)

    sys.argv[0] = 'locust'
    if len(sys.argv) == 1:
        sys.argv.extend(["-h"])

    if sys.argv[1] in ["-h", "--help", "-V", "--version"]:
        main()
        sys.exit(0)
```

**Comment by Junho2010** [comment]
C:\Users\hexia>locust -h
Usage: locust [options] [LocustClass [LocustClass2 ... ]]

Options:
  -h, --help            show this help message and exit
  -H HOST, --host=HOST  Host to load test in the following format:
                        http://10.21.32.33
……
  是正常的，我之前也用过locust做性能测试，使用的时候是没有问题的
