### ISSUE TITLE
ate/testcase.py函数parse_content_with_bindingse举的例子少一个值

### ISSUE THREAD

**Issue by testwangchao** [debugtalk/ApiTestEngine#32]
应该是variables_binds ={
            "authorization": "a83de0ff8d2e896dbd8efb81ba14e17d",
            "random": "A2dEx",
            "data": {"name": "user", "password": "123456"},
            "uid": 1000
        }

**Comment by debugtalk** [comment]
@testwangchao 感谢，已修复。
