### ISSUE TITLE
报告模板 Web 页加载时，部分资源无法加载

### ISSUE THREAD

**Issue by TyouSF** [debugtalk/ApiTestEngine#44]
# 报告模板查看时，会存在如下报错：
```
GET https://ajax.googleapis.com/ajax/libs/jquery.min.js
net::ERR_CONNECTION_TIMED_OUT
```

# 问题：
由于外网的原因，导致可能存在一些用户在使用的时候，无法完成一些报告模板内引用的加载。
导致存在报错信息时，报错内容无法在 web 页面内查看。

# 建议：
能否对一些 js 等的引用改为对国内用户较为友好的方式，方便加载

**Comment by debugtalk** [comment]
@TyouSF 已经将jQuery的CDN源改为`https://ajax.aspnetcdn.com`。

**Comment by TyouSF** [comment]
验证结果：
- 已验证：问题已修复
- 方式：重新更新 PyUnitReport 包
- 版本：PyUnitReport 0.1.2
