### ISSUE TITLE
Package requirement ‘PyUnitReport’ is not satisfied

### ISSUE THREAD

**Issue by wholegale39** [debugtalk/ApiTestEngine#7]
你好，工程clone到本地后，Pycharm中双击打开任何一个.py文件，顶部都提示Package requirement ‘PyUnitReport’ is not satisfied，然后点击Install requirement，安装成功后，依然提示，请大神帮忙看下，感谢

**Comment by debugtalk** [comment]
@wholegale39 `PyUnitReport`依赖包是通过`github`链接的方式进行指定的，估计`PyCharm`不能自动处理这类依赖，你可以通过`pip install -r requirements.txt`的方式安装。

**Comment by wholegale39** [comment]
D:\Python_Project\ApiTestEngine (master)                                                                                                                                
λ pip install -r requirements.txt                                                                                                                                       
Requirement already satisfied: requests in c:\python27\lib\site-packages (from -r requirements.txt (line 1))                                                            
Requirement already satisfied: termcolor in c:\python27\lib\site-packages (from -r requirements.txt (line 2))                                                           
Requirement already satisfied: flask in c:\python27\lib\site-packages (from -r requirements.txt (line 3))                                                               
Requirement already satisfied: PyYAML in c:\python27\lib\site-packages (from -r requirements.txt (line 4))                                                              
Requirement already satisfied: coveralls in c:\python27\lib\site-packages (from -r requirements.txt (line 5))                                                           
Requirement already satisfied: coverage in c:\python27\lib\site-packages (from -r requirements.txt (line 6))                                                            
Obtaining PyUnitReport from git+https://github.com/debugtalk/PyUnitReport.git#egg=PyUnitReport (from -r requirements.txt (line 7))                                      
  Cloning https://github.com/debugtalk/PyUnitReport.git to d:\python_project\apitestengine\src\pyunitreport                                                             
  Running setup.py (path:D:\Python_Project\ApiTestEngine\src\pyunitreport\setup.py) egg_info for package PyUnitReport produced metadata for project name html-testrunner
. Fix your #egg=PyUnitReport fragments.                                                                                                                                 
Requirement already satisfied: idna<2.6,>=2.5 in c:\python27\lib\site-packages (from requests->-r requirements.txt (line 1))                                            
Requirement already satisfied: urllib3<1.22,>=1.21.1 in c:\python27\lib\site-packages (from requests->-r requirements.txt (line 1))                                     
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests->-r requirements.txt (line 1))                                     
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests->-r requirements.txt (line 1))                                        
Requirement already satisfied: itsdangerous>=0.21 in c:\python27\lib\site-packages (from flask->-r requirements.txt (line 3))                                           
Requirement already satisfied: click>=2.0 in c:\python27\lib\site-packages (from flask->-r requirements.txt (line 3))                                                   
Requirement already satisfied: Werkzeug>=0.7 in c:\python27\lib\site-packages (from flask->-r requirements.txt (line 3))                                                
Requirement already satisfied: Jinja2>=2.4 in c:\python27\lib\site-packages (from flask->-r requirements.txt (line 3))                                                  
Requirement already satisfied: docopt>=0.6.1 in c:\python27\lib\site-packages (from coveralls->-r requirements.txt (line 5))                                            
Requirement already satisfied: MarkupSafe>=0.23 in c:\python27\lib\site-packages (from Jinja2>=2.4->flask->-r requirements.txt (line 3))                                
Installing collected packages: html-testrunner                                                                                                                          
  Running setup.py develop for html-testrunner                                                                                                                          
Successfully installed html-testrunner   

这样都运行成功了，还是提示那个问题

**Comment by debugtalk** [comment]
@wholegale39 那你在Python的终端中，输入`import HtmlTestRunner`，看是否正常。如果有报错说明没有安装成功。

**Comment by wholegale39** [comment]
import HtmlTestRunner正常无报错，这样就可以了是吗？

还有在工程目录下运行下面的命令报错
$ python -m unittest discover

Ran 11 tests in 0.505s                                                
                                                                      
FAILED (errors=8)                                                     
                                                                      
Traceback (most recent call last):                                    
  File "<string>", line 1, in <module>                                
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)                                          
  File "C:\Python27\lib\pickle.py", line 1384, in load                
    return Unpickler(file).load()                                     
  File "C:\Python27\lib\pickle.py", line 864, in load                 
    dispatch[key](self)                                               
  File "C:\Python27\lib\pickle.py", line 886, in load_eof             
    raise EOFError                                                    
EOFError

**Comment by debugtalk** [comment]
@wholegale39 从你给的报错来看，都不是框架层的，我不确定你本机的Python环境是否正常。

**Comment by Waylon91** [comment]
D:\>python3 -m pip install git+https://github.com/debugtalk/ApiTestEngine.git#egg=ApiTestEngine
Collecting ApiTestEngine from git+https://github.com/debugtalk/ApiTestEngine.git#egg=ApiTestEngine
  Cloning https://github.com/debugtalk/ApiTestEngine.git to c:\users\admini~1\appdata\local\temp\pip-build-8pcotovx\apitestengine
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-8pcotovx\ApiTestEngine\setup.py", line 11, in <module>
        long_description = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 1439: illegal multibyte sequence

**Comment by ohmydengzi** [comment]
我安装的时候也出现类似情况，是不是参数 -e的导致的？

![image](https://user-images.githubusercontent.com/13642149/28551273-b07b1884-7119-11e7-81de-6bb5818db545.png)
@debugtalk

**Comment by debugtalk** [comment]
貌似在`Linux`和`Windows`上就会出现无法自动安装依赖的问题。可以通过手动安装解决，查看[这里](
https://github.com/debugtalk/ApiTestEngine/blob/master/docs/FAQ.md)。

**Comment by ohmydengzi** [comment]
嗯~~

**Comment by debugtalk** [comment]
已经修复该问题，详情可参考 http://debugtalk.com/post/How-to-install-a-package-from-Github-that-has-other-github-dependencies/

**Comment by firefoxwang** [comment]
win7系统还遇到了ssl的问题 ，https认证不通过
我是这么安装的：
1.clone下项目源码
2.pip install -r requirements_dev.txt --trusted-ho
st pypi.python.org
3.python setup.py install
