### ISSUE TITLE
context的调用是为了做什么？

### ISSUE THREAD

**Issue by diaojunxian** [debugtalk/ApiTestEngine#8]
我有点不明白context里面的类是做什么的，能简单介绍一下吗？还有我能直接复用你的部分代码，到我们项目中吗？

**Comment by debugtalk** [comment]
Context，在程序里面就是运行上下文的含义，里面可以维护变量状态。
在这个框架中，有两层Context，testset层面和testcase层面；testcase层面中的变量只能在当前测试用例执行时使用，而testset层面的变量可以在整个用例集执行时使用。

项目是MIT协议的，欢迎使用。

**Comment by diaojunxian** [comment]
如果我没有在测试用例中定义变量，我不明白，该怎么提取出不需要的部分代码？有点懵了。

-----------------------------------------------------------------------------------------------------------------------
刁俊先｜Junxian Diao
测试工程师｜Test Engineer
华米科技｜HUAMI Co., Ltd.
合肥创新大道2800号创新产业园二期H8楼 (230088）
Building H8, No. 2800 ChuangXin Road, Heifei, China (230088)
手机｜Mobile: +86 186 5635 8366
Email: diaojunxian@huami.com<mailto:diaojunxian@huami.com>
微信号｜WeChat: diaojunxian12345
This email communication is confidential.  Recipient(s) named above is (are) obligated to maintain secrecy and is (are) not permitted to disclose the contents of this communication to others.  If you are not the right person to receive this email, please deleted it immediately.  Thank you!
本邮件载有秘密信息，请您恪守保密义务，勿向第三方透露。如果您不是正确的收件人，请您立即删除此邮件，谢谢合作！


在 2017年7月26日，下午2:22，Leo Lee (九毫) <notifications@github.com<mailto:notifications@github.com>> 写道：


Context，在程序里面就是运行上下文的含义，里面可以维护变量状态。
在这个框架中，有两层Context，testset层面和testcase层面；testcase层面中的变量只能在当前测试用例执行时使用，而testset层面的变量可以在整个用例集执行时使用。

项目是MIT协议的，欢迎使用。
