### ISSUE TITLE
$data能取到值，但是${取不到值}？

### ISSUE THREAD

**Issue by diaojunxian** [debugtalk/ApiTestEngine#9]
在使用过程中，我发现了一个问题，如果在测试用例文件中，config中variable_binds，如果想传入一个公共的参数，类如data=1，然后在test用例中，通过${data}取不到值，只有$data能取到之前的赋值？请问这是我的用例不合要求吗？还是因为什么？

**Comment by diaojunxian** [comment]
我知道了为什么${data}取不到值，还需要增加一个新需求，对于`url=/v/text/$token/$userid`，如果有两个这样的参数存在于url中，实际到请求的时候，代码只会对$userid赋值，但是对$token却没有效果。

**Comment by debugtalk** [comment]
@diaojunxian 在本框架中只存在两种转义符，`$var`代表变量，`${func(a, b)}`代表调用函数，所以`${data}`并没法取到变量值。

第二个问题，的确是当前框架存在的一个bug，在做正则匹配的时候，没有考虑一个字符串中多个变量的情况，后面我修复下。

**Comment by debugtalk** [comment]
当前，在从`YAML/JSON`格式的用例中解析变量和函数的时候，是采用正则表达式匹配的形式，具体匹配方式如下：

```python
variable_regexp = re.compile(r"^\$([\w_]+)$")
function_regexp = re.compile(r"^\$\{([\w_]+)\(([\$\w_ =,]*)\)\}$")
```

因此，如果在某个字符串里面包含多个变量或者多个函数调用，那么正则匹配就会出现问题。

**Comment by diaojunxian** [comment]
@debugtalk 这些看过你的代码，能看出来。

**Comment by debugtalk** [comment]
@diaojunxian 提交代码修复了，你确定没问题的话就关闭这个issue吧。

**Comment by diaojunxian** [comment]
@debugtalk 还是有奇怪的问题，对于这样的url=/users/$userid/data?userId=$userid的确能正确的转换，但是对于url=/users/$userid/training/$data?userId=$userid&data=$data，得到的转换的结果是
url=/users/$userid/training/1498?userId=$userid&data=1498，对于其中的userid却未能转换对应值，我看到你的源码部分应该是，不知道如何改？
```
def parse_template(testcase_template, variables_binds):
    def substitute(content):
        """ substitute content recursively, each variable will be replaced with bind value.
        """
        if isinstance(content, string_type):
            print "+++++++++++++++",content
            return parse_content_with_variables(content, variables_binds)

        if isinstance(content, list):
            print "----------------",content
            return [substitute(item) for item in content]

        if isinstance(content, dict):
            print "vvvvvvvvvvvvvvvvvv",content
            parsed_content = {}
            for key, value in content.items():
                print "=========key=======",key
                print "=========value=====",value

                parsed_content[key] = substitute(value)
            print "======parsed_content======",parsed_content
            return parsed_content

        return content
    return substitute(testcase_template)
```

**Comment by diaojunxian** [comment]
@debugtalk bug应该还是没解决，你写的matched = re.match(r"^(.*)\$(\w+)(.*)$", content)，这里只能匹配一个$userid，对于多个$userid或者$data，还是取不出来。

**Comment by debugtalk** [comment]
@diaojunxian 非常感谢你提的这个issue。
我这边已经对代码进行了重构，彻底解决了这个问题，代码逻辑也比之前清晰多了。
针对你的这个问题，我已经将它加入了单元测试用例中，可以查看 [test_testcase.py](https://github.com/debugtalk/ApiTestEngine/blob/master/tests/test_testcase.py) 中的 `test_parse_content_with_bindings_multiple_identical_variables`。

**Comment by diaojunxian** [comment]
谢谢。我也是一直在用你的代码解决我们的问题。我验证一下。下午我还写了一个while循环去解决，准备提pr的，看来是不需要了，我看看你是怎么实现的 。

**Comment by debugtalk** [comment]
@diaojunxian 在之前的实现中，存在两处解析数据的地方，`parse_content_with_variables`和`parse_variables`，而在我前一次bugfix中，只解决了`parse_variables`中的问题。
现在我经过重构，已经将这两处解析数据的逻辑合并为一个了。

**Comment by diaojunxian** [comment]
@debugtalk 赞，我看到了，我们的某些接口，在请求时候，会需要先进行urlencode编码，比如data={userid=1,dd={test=1,xx=2}}，在请求的时候会变成data=userid=1&dd=urllib.urlencode(dd)这个样子，我需要在你的代码里再新增一个特殊接口请求方式的处理，等我完成，我会提一个pr.
